name: flutter_qdaily_test
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - assets/images/ic_ad.png
      - assets/images/ic_back.png
      - assets/images/ic_back_black.png
      - assets/images/ic_close_black.png
      - assets/images/ic_comment.png
      - assets/images/ic_comment_normal.png
      - assets/images/ic_comment_press.png
      - assets/images/ic_favor.png
      - assets/images/ic_favor_normal.png
      - assets/images/ic_favor_press.png
      - assets/images/ic_lab_join.png
      - assets/images/ic_lab_new.png
      - assets/images/ic_login.png
      - assets/images/ic_menu_about.png
      - assets/images/ic_menu_category.png
      - assets/images/ic_menu_close_x.png
      - assets/images/ic_menu_column.png
      - assets/images/ic_menu_home.png
      - assets/images/ic_menu_lab.png
      - assets/images/ic_menu_msg.png
      - assets/images/ic_menu_night_state.png
      - assets/images/ic_menu_offline.png
      - assets/images/ic_menu_recomend.png
      - assets/images/ic_menu_setting.png
      - assets/images/ic_menu_usercenter.png
      - assets/images/ic_more.png
      - assets/images/ic_net_error.png
      - assets/images/ic_new.png
      - assets/images/ic_night_state.png
      - assets/images/ic_no_data.png
      - assets/images/ic_not_favor.png
      - assets/images/ic_offline.png
      - assets/images/ic_praise_normal.png
      - assets/images/ic_praise_press.png
      - assets/images/ic_recomend.png
      - assets/images/ic_setting.png
      - assets/images/ic_share.png
      - assets/images/ic_share_normal.png
      - assets/images/ic_share_press.png
      - assets/images/ic_close_no_shadow.png
      - assets/images/ic_search.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
